document.write(" <header>");
document.write("    <div class=\"menu-row\">");
document.write("        	<div class=\"main\">");
document.write("<ul id=\"nav\">");
document.write("	<li><a href=\"index.html\">Home<\/a><\/li>");
document.write("	<li><a href=\"#\">Tribute &amp; Live Shows<\/a>");
document.write("		<ul>");
document.write("			<li><a href=\"Abba-glamma.html\">Abba Glamma<\/a><\/li>");
document.write("						<li><a href=\"beyonce.html\">Beyonce<\/a><\/li>");
document.write("            <li><a href=\"decades.html\">Decades<\/a><\/li>");
document.write("            <li><a href=\"Dirty-Dancing.html\">Dirty Dancing<\/a><\/li>");
document.write("            <li><a href=\"fiftyshades.html\">Fifty Shades Ladies Night<\/a><\/li>");
document.write("            <li><a href=\"GaryBarlow.html\">Gary Barlow<\/a><\/li>");
document.write("						<li><a href=\"KevinSimm.html\">Kevin Simm<\/a><\/li>");
document.write("            <li><a href=\"NathanMoore.html\">Nathan Moore<\/a><\/li>");
document.write("            <li><a href=\"robbie.html\">Robbie Williams<\/a><\/li>");
document.write("						<li><a href=\"srj.html\">Shane Richie Jnr.<\/a><\/li>");
document.write("            <li><a href=\"soul&motown.html\">Soul & Motown<\/a><\/li>");
document.write("            <li><a href=\"TotOllyMurs.html\">Totally Olly Murs<\/a><\/li>");
document.write("			<li><a href=\"totallytakethat.html\">Totally Take That<\/a><\/li>");
document.write("		<\/ul>");
document.write("		<div class=\"clear\"><\/div>");
document.write("	<\/li>");
document.write("	<li><a href=\"#\">Theme Nights & DJs<\/a>");
document.write("	<ul>");
document.write("    	<li><a href=\"CasinoNight.html\">Casino Nights<\/a><\/li>");
document.write("		<li><a href=\"ComedyNight.html\">Comedy Nights<\/a><\/li>");
document.write("        <li><a href=\"DecadesDJ.html\">Decades Themed DJ<\/a><\/li>");
document.write("		<li><a href=\"DJs.html\">DJs<\/a><\/li>");
document.write("		<li><a href=\"Pantomimes.html\">Pantomimes<\/a><\/li>");
document.write("	<\/ul>			");
document.write("		<div class=\"clear\"><\/div>");
document.write("	<\/li>");
document.write("	<li><a href=\"#\">Bands\/Duos\/Musicians<\/a>");
document.write("	<ul>");
document.write("    	<li><a href=\"chesquaacoustic.html\">Chesqua Acoustic<\/a><\/li>");
document.write("			<li><a href=\"emilyacoustic.html\">Emily O'Hara Acoustic<\/a><\/li>");
document.write("			<li><a href=\"GroovyRevolution.html\">Groovy Revolution<\/a><\/li>");
document.write("			<li><a href=\"horizonfall.html\">Horizon Fall<\/a><\/li>");
document.write("			<li><a href=\"latinobreak.html\">Latino Break<\/a><\/li>");
document.write("			<li><a href=\"srj.html\">Shane Richie Jnr. SRJ Band<\/a><\/li>	");
document.write("	<\/ul>			");
document.write("		<div class=\"clear\"><\/div>");
document.write("	<\/li>");
document.write("	<li><a href=\"news.html\">News & Events<\/a><\/li>");
document.write("    <li><a href=\"about.html\">About Us<\/a><\/li>");
document.write("	<li><a href=\"contacts.html\">Contact Us<\/a><\/li>");
document.write("<\/ul>");
document.write("<div class=\"clear\"><\/div>");
document.write("       	<\/div>");
document.write("      <\/div>");
document.write("			<\/header>");
